/**
 * Dev-Specific Release Note Generator v1.0
 * Project: CANLK
 * 
 * Focus: Technical depth, component changes, and dev-centric metrics.
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..', '..');
const DEV_DIR = path.join(PROJECT_ROOT, '04_Dev');
const RELEASES_DIR = path.join(DEV_DIR, 'releases');

const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    cyan: '\x1b[36m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    white: '\x1b[37m'
};

function scanDevFolder() {
    const stats = {
        frontend: { components: [], hooks: [], files: 0 },
        backend: { migrations: [], edgeFunctions: [], files: 0 },
        qa: { tests: [], files: 0 }
    };

    if (!fs.existsSync(DEV_DIR)) return stats;

    function walk(dir, category) {
        if (!fs.existsSync(dir)) return;
        const files = fs.readdirSync(dir, { withFileTypes: true });

        for (const file of files) {
            const fullPath = path.join(dir, file.name);
            if (file.isDirectory()) {
                if (file.name === 'node_modules' || file.name === '.git') continue;
                walk(fullPath, category);
            } else {
                stats[category].files++;
                if (category === 'frontend') {
                    if (file.name.includes('Component') || (file.name.match(/[A-Z].*\.tsx?$/) && !file.name.includes('test'))) {
                        stats.frontend.components.push(file.name);
                    } else if (file.name.startsWith('use') && file.name.endsWith('.ts')) {
                        stats.frontend.hooks.push(file.name);
                    }
                } else if (category === 'backend') {
                    if (file.name.endsWith('.sql')) stats.backend.migrations.push(file.name);
                    else if (fullPath.includes('functions')) stats.backend.edgeFunctions.push(file.name);
                } else if (file.name.includes('test') || file.name.includes('spec')) {
                    stats.qa.tests.push(file.name);
                }
            }
        }
    }

    walk(path.join(DEV_DIR, 'frontend'), 'frontend');
    walk(path.join(DEV_DIR, 'database'), 'backend');
    // For QA, we check both as they might be co-located
    walk(path.join(DEV_DIR, 'frontend'), 'qa');
    walk(path.join(DEV_DIR, 'database'), 'qa');

    return stats;
}

function generateDevReleaseNote(stats, version = 'v1.1.0-DEV') {
    const date = new Date().toISOString().split('T')[0];
    let md = `# 🛠️ DEV RELEASE NOTE - CANLK\n\n`;
    md += `**Version:** ${version}\n`;
    md += `**Date:** ${date}\n`;
    md += `**Target:** Development Team / Tech Lead\n\n`;
    md += `---\n\n`;

    md += `## 🎨 FRONTEND (Nexus Architecture)\n\n`;
    md += `- **New Components:** ${stats.frontend.components.length > 0 ? stats.frontend.components.join(', ') : 'None detected'}\n`;
    md += `- **Hooks / Logic:** ${stats.frontend.hooks.length > 0 ? stats.frontend.hooks.join(', ') : 'None detected'}\n`;
    md += `- **Total Files:** ${stats.frontend.files}\n\n`;

    md += `## ⚙️ BACKEND & DATA (MS Engine)\n\n`;
    md += `- **SQL Migrations:** ${stats.backend.migrations.length > 0 ? stats.backend.migrations.join(', ') : 'None detected'}\n`;
    md += `- **Edge Functions:** ${stats.backend.edgeFunctions.length > 0 ? stats.backend.edgeFunctions.join(', ') : 'None detected'}\n`;
    md += `- **Total Files:** ${stats.backend.files}\n\n`;

    md += `## 🧪 QA & STABILITY (Sentinel)\n\n`;
    md += `- **Test Contexts:** ${stats.qa.tests.length > 0 ? stats.qa.tests.join(', ') : 'None detected'}\n`;
    md += `- **Framework:** Vitest / Playwright detected\n\n`;

    md += `---\n\n`;
    md += `## ⚠️ TECHNICAL DEBT & NOTES\n\n`;
    md += `- [ ] Verification of RLS policies for new migrations\n`;
    md += `- [ ] Check component re-renders for heavy forms\n`;
    md += `- [ ] Sync required for Jira metadata\n\n`;

    md += `---\n`;
    md += `*Generated by CANLK Dev-Agent v1.0*\n`;

    return md;
}

function main() {
    console.log(`\n${colors.bright}${colors.cyan}🚀 CANLK DEV RELEASE GENERATOR${colors.reset}\n`);
    
    const stats = scanDevFolder();
    console.log(`${colors.green}✓${colors.reset} Scanned 04_Dev folder`);
    
    const content = generateDevReleaseNote(stats);
    
    if (!fs.existsSync(RELEASES_DIR)) {
        fs.mkdirSync(RELEASES_DIR, { recursive: true });
    }
    
    const fileName = `dev_release_${new Date().toISOString().split('T')[0]}.md`;
    const fullPath = path.join(RELEASES_DIR, fileName);
    
    fs.writeFileSync(fullPath, content, 'utf8');
    
    console.log(`${colors.green}✓${colors.reset} Generated technical release note: ${colors.white}${fileName}${colors.reset}\n`);
    console.log(`${colors.yellow}Location:${colors.reset} ${fullPath}\n`);
}

main();
